# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12874e97822c046d323fc26abf4040efb153f492ed5975b1351e38529bd2fdabae84c52bd9968f7c6dc17ad8a25c16ae2d8575609a3d6523fff4fd46f6780da9

test:
  secret_key_base: e1436eaac9aa8083f87e93879c5cb5a05694d8466a2c4cd4a4654065e88d27f01266190d98c11c5c11543502bc1b7faa2be07196af978b655acea9ae537362f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
